### ISSUE TITLE
MozacFetch/49.0.20200702190156 was wrongly recognised as a bot

### ISSUE THREAD

**Issue by simontabor** [omrilotan/isbot#117]
## User Agent String
`MozacFetch/49.0.20200702190156`

## Reproduce
MozacFetch appears to be the user agent used by Mozilla's new Android browser - Fenix - https://stackoverflow.com/questions/63666913/where-is-this-user-agent-from-mozacfetch

I have no Android phone or Fenix build, so I'm unable to reproduce right now. Looking at https://github.com/mozilla-mobile/fenix/issues/7961, Fenix uses MozacFetch UA under certain situations, so it's not a crawler.

**Comment by omrilotan** [comment]
Looking into this

**Comment by omrilotan** [comment]
By installing Firefox Nightly for Android I'm receiving user agent string:
```
Mozilla/5.0 (Android 10; Mobile; rv:86.0) Gecko/86.0 Firefox/86.0
```

@simontabor Do you have an installation link?

**Comment by omrilotan** [comment]
What were the circumstances you've encountered it? I can not see a reference in their codebase

**Comment by omrilotan** [comment]
Found in Mozilla android components https://github.com/mozilla-mobile/android-components/search?q=MozacFetch . I will issue a fix promptly

**Comment by simontabor** [comment]
Ah, good find. Thanks so much @omrilotan

**Comment by omrilotan** [comment]
Fixed in 3.0.22

**Comment by omrilotan** [comment]
Sorry, my mistake, fined in 3.0.23

**Comment by omrilotan** [comment]
Verify here: https://isbot.js.org/?ua=MozacFetch/49.0.20200702190156
