### ISSUE TITLE
Chrome was wrongly recognised as a bot

### ISSUE THREAD

**Issue by spartanz51** [omrilotan/isbot#127]
## User Agent String

Mozilla/5.0 (Linux; Android 10; SM-G973F Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36 trill_2021806060 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/18.6.6 ByteLocale/fr ByteFullLocale/fr Region/FR

This user agent is from Tiktok webview, on Android
It seems that the string "google" is triggering your pattern

## Reproduce
Open tiktok
Open a link in user bio: you are detected as a bot

**Comment by omrilotan** [comment]
Thank you for this ticket. Issue was addressed in isbot@3.0.25
[Review](https://isbot.js.org/?ua=Mozilla/5.0%20(Linux;%20Android%2010;%20SM-G973F%20Build/QQ3A.200805.001;%20wv)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/85.0.4183.101%20Mobile%20Safari/537.36%20trill_2021806060%20JsSdk/1.0%20NetType/WIFI%20Channel/googleplay%20AppName/musical_ly%20app_version/18.6.6%20ByteLocale/fr%20ByteFullLocale/fr%20Region/FR)
