### ISSUE TITLE
nibbler

### ISSUE THREAD

**Issue by tonprince** [omrilotan/isbot#145]
## User Agent String
nibbler

## Reproduce
I tested on my website and nibbler is not recognized as a bot.

https://nibbler.silktide.com/en/about

**Comment by omrilotan** [comment]
Will be resolved in version 3.0.27 for user agent "nibbler". Not for user agent "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3" which is mentioned in its documentation

https://isbot.js.org/?ua=nibbler

**Comment by tonprince** [comment]
Thanks
