### ISSUE TITLE
[3.3.1] "const" keyword in index.js

### ISSUE THREAD

**Issue by jlowcs** [omrilotan/isbot#160]
Steps to reproduce
-------
Build an app with webpack using this library.

Expected behaviour
-------
index.js should contain ES5 code for full browser support.

Actual behaviour
-------
index.js contains one `const` keyword, and therefore webpack generated a bundle/chunk with a `const` keyword.

![image](https://user-images.githubusercontent.com/3777724/129906089-c923bde3-089c-4a42-a934-96b5ae06c88d.png)

Additional details
-------

**Comment by jlowcs** [comment]
looks like there are even more of those in the 4.0.0 rc btw:

![image](https://user-images.githubusercontent.com/3777724/129909266-f3303b38-e6a2-4e24-b61c-7d3bacad529d.png)

**Comment by omrilotan** [comment]
Fix proposed: https://github.com/omrilotan/isbot/pull/161
Would appreciate your review.

Don't worry about 4.0.0 rc. This specific breaking version will not be released.

**Comment by omrilotan** [comment]
Resolved in 3.3.2
| ![](https://user-images.githubusercontent.com/516342/130212781-c90c0be2-a521-4c10-928d-c44ae11a21f6.png)
| -
