### ISSUE TITLE
Pattern not being removed when calling "exclude"

### ISSUE THREAD

**Issue by jannone** [omrilotan/isbot#166]
Steps to reproduce
-------
```
const isBot = require('isbot');

const userAgent = 'Mozilla/5.0 (Linux; Android 10; SNE-LX1 Build/HUAWEISNE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36 hap/1079/huawei com.huawei.fastapp/11.4.1.310 com.bla.quickapp/4.0.17 ({"packageName":"quickSearch","type":"other","extra":"{}"})';

isBot.exclude(['search']);

console.log(isBot(userAgent));
console.log(isBot.find(userAgent));
```

Expected behaviour
-------
`search` should have been removed from the pattern list,
and the example userAgent should have not be identified as a bot.

Actual behaviour
-------
`search` is still kept in the pattern list,
and the userAgent is still identified as a bot.

**Comment by omrilotan** [comment]
I think I have a good solution for this in #167. Care to take a look?

**Comment by jannone** [comment]
I'm unsure... In my scenario, do I need to exclude both expressions? If so, #167 might not solve it... since it only returns the first expression that is found, rather than an array of expressions

**Comment by omrilotan** [comment]
Updated the pull request to include new functionality

https://github.com/omrilotan/isbot/pull/167

> Add "matches" and "clear" methods used to clear patterns matching a user agent string.
> 
> This will be a suitable solution for such cases. The example below includes extra steps to display the journey.
> 
> For example:
> 
> ```js
> const ua = 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0 SearchRobot/1.0'
> 
> sbot(ua) // true
> isbot.find(ua) // 'Search'
> isbot.matches(ua) // [ '(?<! cu)bot', '(?<! (ya|yandex))search' ]
> isbot.clear(ua)
> isbot(ua) // false
> isbot.find(ua) // null
> ```

**Comment by jannone** [comment]
Good catch! I hadn't seen the white space. It works now
