### ISSUE TITLE
Support for Chrome/Firefox 100

### ISSUE THREAD

**Issue by bmustata** [omrilotan/isbot#172]
How this is going to support Chrome and Firefox version 100?
https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

**Comment by omrilotan** [comment]
I don't understand the question. Why would there be an issue with version 100?
We don't parse the user agent string. We search for known patterns:

isbot: [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0](https://isbot.js.org/?ua=Mozilla%2F5.0+(Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A100.0)+Gecko%2F20100101+Firefox%2F100.0)

**Comment by bmustata** [comment]
Chrome will reduce the amount of information available in the User Agent string so i understand that after ver 100 this will not be affected.

**Comment by omrilotan** [comment]
Tested with Chrome's flag `#force-major-version-to-100` (under chrome://flags) and added appropriate tests #173
