### ISSUE TITLE
Calling method isbot() return isbot_namespaceObject is not a function

### ISSUE THREAD

**Issue by adnanebrahimi** [omrilotan/isbot#174]
Steps to reproduce
-------
npm install isbot --save

in expressjs:
```
server.get('*', (req, res) => {
    if (isbot(req.header('User-Agent'))) {
      console.log('bot and running on SSR');
    res.render(indexHtml, {
      req,
      providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }, provideLocation(req), provideUserAgent(req)],
    });
   } else {
      console.log('No SSR');
      // No SSR
      // return index.html without pre-rendering
      // app will get rendered on the client
      res.sendFile(path.join(__dirname, '../browser/index.html'));

    }
  });
```
Expected behaviour
-------
by browser loads webapp as CSR

by bot loads webapp as SSR

Actual behaviour
-------
error occured:

TypeError: isbot_namespaceObject is not a function

Additional details
-------
Angular Universal Version 13

**Comment by omrilotan** [comment]
Thank you, [Adnan](https://github.com/adnanebrahimi).
Will you be able to send a dependency and deploy pipeline to reproduce?
I'll try to reproduce and resolve this issue promptly

**Comment by adnanebrahimi** [comment]
I fixed by changing an option in tsconfig to have correct import:
in tsconfig.json
`"allowSyntheticDefaultImports": true`

in server.ts:
`import isbot from 'isbot';`

the wrong import was:
`import 8 as isbot from 'isbot';`

Thanks for your fast reply 👌
