### ISSUE TITLE
need umd version

### ISSUE THREAD

**Issue by Augensternhx** [omrilotan/isbot#204]
Steps to reproduce
-------

Expected behaviour
-------

Actual behaviour
-------

Additional details
-------

**Comment by omrilotan** [comment]
Hey, @Augensternhx , thanks for reaching out.
What is the UMD version used for?
This package exports both CommonJS and ES module, what is the use case you need here?

https://github.com/omrilotan/isbot/blob/main/package.json#L24-L41

**Comment by Augensternhx** [comment]
When I use this in my browser
> https://cdn.jsdelivr.net/npm/isbot@3.6.6/index.min.js

I will get tips like this 
> Uncaught ReferenceError: module is not defined

It looks like there is a lack of UMD version, here is the introduction about UMD
> http://jargon.js.org/_glossary/UMD.md

If you use rollup, this is a simple example
```javascript
{
    input: './demo.js',
    output: {
      file: './demo.min.js',
      format: 'umd',
    }
 }
```

**Comment by omrilotan** [comment]
if I understand correctly, you want "isbot" to be made available as a global variable once you include this script tag in your page.
I'm not the one publishing to jsdeliver network, but you can use this script from their CDN as a module:

```html
<!doctype html>
<html>
  <body>
    <div></div>
    <script type="module">
      import isbot from "https://cdn.jsdelivr.net/npm/isbot@3.6.6/index.min.mjs";
      const is = isbot(navigator.userAgent);
      document.querySelector("div").innerText = `User agent: "${navigator.userAgent}" is ${is ? "" : "not "}a bot`;
    </script>
  </body>
</html>
```

https://jsfiddle.net/omrilotan/geud63of/
![](https://user-images.githubusercontent.com/516342/222988664-50709bf4-ead3-4620-bc8e-bf593cdbba55.png)

Is this satisfactory?

**Comment by Augensternhx** [comment]
```type="module"```
 This only works with modern browsers，This is not an effective solution

**Comment by omrilotan** [comment]
I did not create a global variable entry, but I'm open to pull requests if you are very interested.
At the moment, I assume most users will bundle the package when building their project, and global variable entries are not usually needed.

**Comment by omrilotan** [comment]
Let me know what you think of this resolution: https://github.com/omrilotan/isbot/pull/205

```md
## [3.7.0](https://github.com/omrilotan/isbot/compare/v3.6.6...v3.7.0)
-   Add a UMD build: /index.umd.js
```
