### ISSUE TITLE
Lighthouse was not recognised

### ISSUE THREAD

**Issue by cortopy** [omrilotan/isbot#213]
User Agent String
-------
Mozilla/5.0 (Linux; Android 11; moto g power (2022)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36

Reproduce
-------
1. Go to `https://pagespeed.web.dev/`
2. Run analysis of a website. I'm getting visits with browser using the User Agent
3. You may verify User Agent by hovering on the information of the report as per screenshot attached

![Screenshot from 2023-07-01 17-39-27](https://github.com/omrilotan/isbot/assets/8725825/af011c42-1461-4b7e-8922-5f4b52ca0078)

**Comment by omrilotan** [comment]
In my experience, all tests from https://pagespeed.web.dev/ use the `Chrome-Lighthouse` substring to identify as bot.

Examples:
- `Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Mobile Safari/537.36 Chrome-Lighthouse`
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4590.2 Safari/537.36 Chrome-Lighthouse`

[Check example on isbot.js.org](https://isbot.js.org/?ua=Mozilla/5.0%20(Linux;%20Android%207.0;%20Moto%20G%20(4))%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/94.0.4590.2%20Mobile%20Safari/537.36%20Chrome-LighthouseMozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/94.0.4590.2%20Safari/537.36%20Chrome-Lighthouse)

![](https://github.com/omrilotan/isbot/assets/516342/201eb570-9a0c-4eee-b3cf-993aeb47d958)

**Comment by omrilotan** [comment]
Any way, you refer to the README [clarifications](https://github.com/omrilotan/isbot#clarifications):

> ## What does "isbot" do?
> This package aims to identify "Good bots". Those who voluntarily identify themselves by setting a unique, preferably descriptive, user agent, usually by setting a dedicated request header.
> ## What doesn't "isbot" do?
> It does not try to recognise malicious bots or programs disguising themselves as real users.

If a tool uses legitimate browser user agent string with no indication of being an automated service - we can not use this tool to identify it.

Continuing in [clarifications](https://github.com/omrilotan/isbot#clarifications) section:

> ...other methods of identification can be added such as [reverse dns lookup](https://www.npmjs.com/package/reverse-dns-lookup).

**Comment by omrilotan** [comment]
I can see Pagespeed have decided to not recognise themselves as a bot using the user agent string. Also mentioned in discussion #214
