### ISSUE TITLE
Extending Postman does nothing

### ISSUE THREAD

**Issue by jabranr** [omrilotan/isbot#216]
I am trying to mark requests from Postman in development as a recogonized bot but it never works.

Steps to reproduce
-------
```
import isbot from 'isbot';

isbot.extend(['postmanruntime', 'postman']);
isbot('PostmanRuntime/7.32.3');
```

Expected behaviour
-------
```
isbot('PostmanRuntime/7.32.3'); // false
```

Actual behaviour
-------
```
isbot('PostmanRuntime/7.32.3'); // true
```

**Comment by omrilotan** [comment]
Seems like it's behaving correctly

True = recognised bot

**Comment by omrilotan** [comment]
This user agent will also be recognised with built in pattern

https://isbot.js.org/?ua=PostmanRuntime/7.32.3

**Comment by jabranr** [comment]
@omrilotan Ah, I get it now. It is merely validating if it is a bot or not. I don't know why I was under the impression that it will recognize it as a browser UA when extended. Thanks for clarifying!
