### ISSUE TITLE
Is there a version available that doesn't require NPM?

### ISSUE THREAD

**Issue by cvocvo** [omrilotan/isbot#217]
Steps to reproduce
-------
We're using Umbraco (ASP.NET Core) with [Smidge ](https://docs.umbraco.com/umbraco-cms/reference/configuration/runtimeminificationsettings) to deliver javascript bundles to client devices. Is there a version of isbot that doesn't require NPM?

Thank you!

**Comment by omrilotan** [comment]
Not at the moment but I'm open to suggestions. What alternative way would you have liked to consume the built version?

**Comment by cvocvo** [comment]
Thanks for the quick response; ideally just a regular old `.js` file would be great. Then this can be included in the Smidge bundle, however, it also opens the door to other users who are just building websites with regular `<script src="/js/somejslib.js"></script>` files. I'm thinking of stuff like Bootstrap where you can just pull in JS and CSS manually without the complexity of NPM and pipelines like ESBuild/Babel/NX. I don't know the right way to describe these JS libraries/frameworks where they're just stand-alone JS files that get included. [IIFE ](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) comes to mind but I don't know if that's precisely it.

**Comment by omrilotan** [comment]
Would you expect this file to expose "isbot" as a global variable then (see following example)?

```html
<script src="https://cdn.js/isbot.js"></script>
<script>
console.log(isbot(navigator.userAgent))
</script>
```

**Comment by cvocvo** [comment]
Yes that would be great

**Comment by omrilotan** [comment]
Okay, I've inspected JSDeliver as a CDN.

You can import and use the module on your web page already using the "mjs" version.

```html
<script type="module">
import isbot from "https://cdn.jsdelivr.net/npm/isbot/index.mjs";

console.log(isbot(navigator.userAgent));
</script>
```

Other than that - I can create an iife version to be imported via JSDeliver CDN as well.

**Comment by omrilotan** [comment]
See https://github.com/omrilotan/isbot/pull/218

**Comment by cvocvo** [comment]
That's fantastic; I think the IIFE version will let me drop it into Smidge. I haven't figured out how to bundle all my JS together and then import the module (because the JS is all getting loaded before via `<script src=`).

**Comment by omrilotan** [comment]
You can now use the iife script straight from this CDN or download it to your machines

```html
<script src="https://cdn.jsdelivr.net/npm/isbot/index.iife.min.js"></script>
```
