### ISSUE TITLE
Ghostery (Ads) was wrongly recognised as a bot

### ISSUE THREAD

**Issue by TigersWay** [omrilotan/isbot#221]
User Agent String = "Mozilla/5.0 (Android 11; Mobile; rv:105.0; Ghostery:3.0) Gecko/105.0 Firefox/105.0"

Reproduce = [test](https://isbot.js.org/?ua=Safari/600.2.5%20MobileRicardo%20(Google%20Pixel%206;%20android%2013)%20ricardo.ch/8.28.2-82802%20(debug)%20deviceId/dfa51331-fdeb-46d7-aa01-8d09a263ef90)

Ghostery seems to be an ads blocker, not a bot

Thanks!

PS: just found also: "Mozilla/5.0 (Android 10; Mobile; rv:109.0; Ghostery:3.0) Gecko/115.0 Firefox/115.0"

**Comment by omrilotan** [comment]
Thank you for this issue. Would you care to review #223 ?
