### ISSUE TITLE
CFNetwork was not recognised

### ISSUE THREAD

**Issue by Kikobeats** [omrilotan/isbot#238]
User Agent String
-------

```
SpringBoard/50 CFNetwork/1209 Darwin/20.2.0
Add%20to%20Are.na/2 CFNetwork/1485 Darwin/23.1.0
SpringBoard/50 CFNetwork/1240.0.4 Darwin/20.6.0
SpringBoard/50 CFNetwork/1206 Darwin/20.1.0
```

Reproduce
-------

I detected this from [top-user-agents](https://github.com/microlinkhq/top-user-agents), I reported this previously (https://github.com/omrilotan/isbot/issues/231) but It seems detecting for `CFNetwork` is going to drop all of them.

**Comment by omrilotan** [comment]
The CFNetwork framework is used by many Apple developers with their applications. It does not imply the request was done by an automated service.

In this case, "SpringBoard" is the name of the application (the application that manages the iOS home screen) and "CFNetwork" is the framework used to make requests.

On issue #233 it was specified:
> I have decided to not treat "SpringBoot" or "retweet" as bots. They seem to be user agents for handheld devices' applications - these are not considered self-identifying automated tools.

**Comment by omrilotan** [comment]
Added mentioned repo as a source of bot UA strings: https://github.com/omrilotan/isbot/pull/239

**Comment by Kikobeats** [comment]
makes sense, thanks!
