### ISSUE TITLE
v4.x.x is not working with Safari 15 and below 

### ISSUE THREAD

**Issue by cieniawska** [omrilotan/isbot#242]
Steps to reproduce
-------
1. Open Safari v15.x.x or below. 
2. Open any app that uses `isbot` function.
3. See the following error appear:
<img width="384" alt="Screenshot 2024-02-15 at 15 50 10" src="https://github.com/omrilotan/isbot/assets/95585601/32ba9452-bfa3-475a-97f1-64763596f4ab">

this is how we use this function:
```
import { isbot } from 'isbot';
import { isUnsupportedBrowser } from '../functions/isUnsupportedBrowser/isUnsupportedBrowser';

const useSupportedBrowser = (): { isSupportedBrowser: boolean } => {
  const isSupportedBrowser: boolean = (
    !isbot(navigator.userAgent) &&
    !isUnsupportedBrowser()
  );

  return { isSupportedBrowser };
};

export default useSupportedBrowser;

```

Anything we can do to solve this issue?

**Comment by omrilotan** [comment]
Thank you for the issue. Can you please check which version specifically?

I added a fallback for unsupportive engines on [4.4.0](https://github.com/omrilotan/isbot/blob/main/CHANGELOG.md#440) that should have taken care of this issue specifically.

**Comment by omrilotan** [comment]
I was able to reproduce it.
Proposed resolution: #243

**Comment by omrilotan** [comment]
Resolution of isbot@5 tested on Safari 15.6

**Comment by omrilotan** [comment]
Thank you, @cieniawska, I'm having trouble reproducing this. If you could provide any more information, I'd love to introduce a patch for it.

**Comment by omrilotan** [comment]
I'll try and test #244 on BrowserStack. Thanks
