### ISSUE TITLE
Zip Recruiter Job Search phone app was wrongly recognised as a bot

### ISSUE THREAD

**Issue by JohnathanSwan** [omrilotan/isbot#247]
User Agent String
-------
Job Search/24.4.0 Mozilla/5.0 (Linux; Android 14; SM-S918U Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

Job Search/95.0 (iPhone; CPU iOS 17_3_1 like Mac OS X)

Reproduce
-------
I couldn't reproduce this because the Iphone app is limited to the US. But this is something that came up at $WORK where we were wrongly marking this app as a bot, it's due to the `(?<! ya(?:yandex)?)search` pattern.

https://apps.apple.com/us/app/ziprecruiter-job-search/id541933937
https://play.google.com/store/apps/details?id=com.ziprecruiter.android.release&hl=en&gl=US

We have manually excluded this agent from our checks at work, but I wondered if adding it to the negative lookbehind would be the solution. Happy to open a PR but I couldn't get the tests running for some reason so thought I would start with an issue report.

Many thanks
Johnathan

**Comment by omrilotan** [comment]
Thank you for the issue.
Addressed in #248

**Comment by JohnathanSwan** [comment]
Thanks!
