### ISSUE TITLE
<NAVER Application> was wrongly recognised as a bot

### ISSUE THREAD

**Issue by davidwin3** [omrilotan/isbot#250]
User Agent String
-------

Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/605.1 NAVER(inapp; search; 2000; 12.3.6; 14PRO)

Reproduce
-------

My iPhone's Naver Application user-agent is being identified as a bot.

1. Install Naver Application in App Store. ([link](https://apps.apple.com/kr/app/%EB%84%A4%EC%9D%B4%EB%B2%84-naver/id393499958))
2. Open https://isbot.js.org/
3. It comes 'I think so, yes'

Thank you.

**Comment by omrilotan** [comment]
Thank you for the ticket. I'll try to address it soon

**Comment by omrilotan** [comment]
Resolved in [5.1.4](https://github.com/omrilotan/isbot/releases/tag/v5.1.4)
