### ISSUE TITLE
Instagram and Safari browsers was wrongly recognised as a bot

### ISSUE THREAD

**Issue by fluteboi** [omrilotan/isbot#254]
The following browsers are wrongly recognised as bots.

User Agent String
-------
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML,like Gecko) Mobile/21F79 Instagram 330.0.3.29.91 (iPhone14,3; iOS 17_5; en_IR@calendar=gregorian; en; scale=3.00; 1125x2436; 595323416)
Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML,like Gecko) Version/17.4.1 Mobile/15E148 Safari/605.1.15 NewsSapphire/1.0.420507003
Mozilla/5.0 (iPhone; CPU iPhone OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML,like Gecko) Version/16.6.1 Mobile/15E148 Safari/605.1.15 NewsSapphire/1.0.420507003

**Comment by omrilotan** [comment]
Thank you for the issue. I have created a changeset to address it #255

**Comment by fluteboi** [comment]
Thank you for the update!

**Comment by omrilotan** [comment]
Fix released in [isbot@5.1.7](https://www.npmjs.com/package/isbot/v/5.1.7)

Thanks again for sharing your findings
