### ISSUE TITLE
Flutter & one other UA was wrongly recognised as a bot

### ISSUE THREAD

**Issue by sagrawal31** [omrilotan/isbot#266]
User Agent String
-------
- `Mozilla/5.0 (Linux; Android 14; I2208 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36 csh-cashify-flutter csh-store-checkout d2c-back-supported`
- `Windows NT 6.1`

These two user agents are identified as bots.

Reproduce
-------
No direct way.

Context
-------

I can confirm that these were the real users browsing a website based on their IP geolocation and activities they did on the websites.

![image](https://github.com/user-attachments/assets/ecdd5d55-a258-4cb0-9a35-55afdea42ef2)

**Comment by omrilotan** [comment]
Addressed Flutter in #265

`Windows NT 6.1` is OS identification only, without browser recognition. It's probably Windows Server.

The user-agent string is not a behavioural check - it is an umbrella check for patterns used by automated services. You can always send and user agent string with your natural behaviour.

**Comment by sagrawal31** [comment]
Thank you, @omrilotan, for addressing my three user-agents so quickly. Much appreciated.

You are suggesting that `Windows MT 6.1` should be kept treating as a bot?

**Comment by omrilotan** [comment]
At this moment, I would keep recognising `Windows MT 6.1` as bot

**Comment by omrilotan** [comment]
Resolved in #265
