### ISSUE TITLE
Few user agents were wrongly recognised as a bot

### ISSUE THREAD

**Issue by sagrawal31** [omrilotan/isbot#269]
User Agent String
-------
- `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 ||| ReqID: 472 | TabID: 643408467 | FrameID: 0 | ParentFrameID: -1 | Type: xmlhttprequest | Time: 1722598417470 | Initiator: https://bummer.in` (because of `http` term)
- `Mozilla/5.0 (Linux; Android 10; STK-L21 Build/HUAWEISTK-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.186 Mobile Safari/537.36HiSearch/22.0.6.315` (`because of `search` term)
- `Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21F90 [FBAN/FBPageAdmin;FBAV/400.0.0.21.108;FBBV/620787505;FBDV/iPhone15,3;FBMD/iPhone;FBSN/iOS;FBSV/17.5.1;FBSS/3;FBID/phone;FBLC/en_GB;FBOP/5;FBDI/D9016741-C75C-4FC3-8A3B-34249A953D07;FBRV/0]` (because of `admin` term)
- `Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Version/17.5.1 Safari/605.1.15 (AirWatch Browser v24.06)` (because of `watch` term)

Reproduce
-------
These four user agents are identified as bots. I don't know how to reproduce this. I can confirm that these were the real users browsing a website based on their IP geolocation and activities they did on the websites.

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/ecb5e867-057b-4e7c-a66a-6e35d2ba9f1b">

**Comment by omrilotan** [comment]
Thank you. I will review these user agent strings and suggest the appropriate changes to the pattern

**Comment by omrilotan** [comment]
Thank you. I've been able to recognise all but the first one, which seems like a glitch.

The entire string, `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 ||| ReqID: 472 | TabID: 643408467 | FrameID: 0 | ParentFrameID: -1 | Type: xmlhttprequest | Time: 1722598417470 | Initiator: https://bummer.in/` includes additional data after the user agent string

Addressed in PR #271

**Comment by sagrawal31** [comment]
Thanks a lot, @omrilotan for taking this up and getting fixed.
