### ISSUE TITLE
Snapchat InApp Browser was wrongly recognised as a bot

### ISSUE THREAD

**Issue by sagrawal31** [omrilotan/isbot#274]
User Agent String
-------
- `Mozilla/5.0 (Linux; Android 11; RMX2001 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36 Snapchat/12.87.0.44 (RMX2001; Android 11#1647528410731#30; gzip; )`
- `Mozilla/5.0 (Linux; Android 13; I2011 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.54 Mobile Safari/537.36 Snapchat/12.89.0.40 (I2011; Android 13#eng.compil.20240430.095616#33; gzip; )`
- 

Reproduce
-------

No steps to reproduce but their activities suggests the same-
![image](https://github.com/user-attachments/assets/132ef8cd-b794-4a34-a082-0be344e6aa4a)

**Comment by omrilotan** [comment]
Thank you. Addressed in #276
