### ISSUE TITLE
CamScanner was wrongly recognised as a bot

### ISSUE THREAD

**Issue by sagrawal31** [omrilotan/isbot#275]
User Agent String
-------
- `Mozilla/5.0 (Linux; Android 13; 2201116SI Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36 CamScanner/4.5.0.2305051722`
- `Mozilla/5.0 (Linux; Android 14; SM-S918B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36 CamScanner/4.8.5.2310271827`

Reproduce
-------
There are no steps, but their activities and IP suggest that these aren't the bots.
![image](https://github.com/user-attachments/assets/cc5585d7-0ebd-47dc-86ce-4da379ed3d00)

**Other references**

- https://www.browserscan.net/user-agent treat this UA as a bot.
- https://github.com/monperrus/crawler-user-agents doesn't treat this as a bot.

**Comment by omrilotan** [comment]
Thank you. Addressed in #276
