### ISSUE TITLE
Chrome OS is not identified

### ISSUE THREAD

**Issue by lymanepp** [omrilotan/isbot#281]
Steps to reproduce
-------
The following user agent is not identified as Chrome OS:

 `Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`

Expected behaviour
-------
The OS should be detected as `Chrome OS`

Actual behaviour
-------
OS and Platform are null

Additional details
-------

**Comment by omrilotan** [comment]
Thank you for opening an issue.
Could you please share a code example of your usage? I don't know if this package does what you expect.

**Comment by lymanepp** [comment]
I'm sorry. This should've been submitted for `bowser` not for `isbot`.
