### ISSUE TITLE
Have more stability for exclusions

### ISSUE THREAD

**Issue by sebranly** [omrilotan/isbot#68]
Hi again, I have another suggestion regarding improving this package.

### Context

I have been using [`extend`](https://github.com/gorangajic/isbot#extending-more-user-agents) which works great. I recently started using [`exclude`](https://github.com/gorangajic/isbot#excluding-known-crawlers) and would like to raise a concern about the way it works. My goal was considering a known crawler, let's say Chrome Lighthouse, as a human. So I needed to exclude it. Using `isBot.exclude(['Lighthouse']);` wouldn't work and when double-checking the documentation, I understood my mistake and used `Chrome-Lighthouse`  (coming from https://github.com/gorangajic/isbot/blob/master/list.json) instead of `Lighthouse` and it's now working as expected.

### Problem

I think this solution is not really stable because I cannot know for sure that `https://github.com/gorangajic/isbot/blob/master/list.json` won't evolve for `Chrome-Lighthouse` (there are other more complex examples). If the string gets updated in `https://github.com/gorangajic/isbot/blob/master/list.json` but doesn't get updated on my application, then the exclusion won't work anymore.

### Solution

I think the best would be to use enumerations that we can import from this package. So instead of using `'Chrome-Lighthouse'` string in `list.json`, something like `UA.LIGHTHOUSE` will be used. Then in my application, I can import this enumeration and use it. This way, by not using hardcoded strings, I know they will always be in sync even when updating the package version.

Please let me know what you think. Thank you in advance!

**Comment by omrilotan** [comment]
Hi, @sebranly. Thank you for taking the time, that's an interesting notion. I'm [considering a little re-think regarding the bot list](https://github.com/gorangajic/isbot/issues/65) that is more content than structure but maintaining the classification in a structured enumerator may have more benefits, I agree.
I don't have a timeline for this but I can inform you as I progress, or if you want to take this on that can happen, too.

**Comment by omrilotan** [comment]
I've looked into this issue. At one point I considered to recommend using the "find" method:
```js
const lhua = 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36(KHTML, like Gecko) Chrome/69.0.3464.0 Mobile Safari/537.36 Chrome-Lighthouse';
isbot(lhua) // true
isbot.exclude([
  isbot.find(lhua) // finds the matched string
])
isbot(lhua) // false
```

But will not work for all rules.
Since I'm constantly trying to improve runtime execution by finding common denominators, I don't think it'll be sustainable to categorise the list.

I'll have to consider how to approach this, because the list is not considered a formal part of the API at the moment.

**Comment by omrilotan** [comment]
Closing this issue
This comment should be considered as the widely used solution: https://github.com/omrilotan/isbot/issues/68#issuecomment-721192815
